### ISSUE TITLE
Release the conversion script?

### ISSUE THREAD

**Issue by ftrotter** [mhess126/usda_national_nutrients#2]
So that we can see how you did the conversion? This way we can maintain updates ourselves...

Thanks for the project!!

-FT

**Comment by nikolov-tmw** [comment]
I would also be interested in that, or if you can let us know whether you'd be publishing updates as they come out(well, not immediately, but you know - in a month or two or three after a new release :smiley: ).

Again - you saved me tons of time having to figure out how to convert the Access database file that I have into MySQL, so lots of thanks for that!

Nikola

**Comment by krowinski** [comment]
+1

**Comment by frazras** [comment]
+1

**Comment by jackmcdade** [comment]
+1 - We're on SR28 now and there is no reliable way to get from the ASCII version to a SQL compatible version.
